global:
  scrape_interval: 15s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - localhost:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: python-app
    static_configs:
      - targets: ["127.0.0.1:3001"]
  - job_name: node-exporter
    static_configs:
      - targets: ["localhost:9100"]